package io.github.nishadchayanakhawa.taskvault.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a resource in the TaskVault system. This entity is used to store
 * resource.
 */
@Entity
@Table(name = "TV_RESOURCE", // Maps this entity to the "TV_RESOURCE" table in the database
		uniqueConstraints = { @UniqueConstraint(name = "UNIQUE_TV_RESOURCE_NAME", // Ensures unique names for resource
				columnNames = { "NAME" } // Applies the constraint to the "NAME" column
		) })
@Getter
@Setter
@NoArgsConstructor
public class Resource {

	/**
	 * Unique identifier for the resource. This value is automatically generated by
	 * the database.
	 */
	@Id
	@GeneratedValue
	private Long id;

	/**
	 * Name of the resource. This is a mandatory field and must not be blank.
	 */
	@NotBlank(message = "Resource name is required")
	private String name;
}
