name: Verify API

on: 
  push:
    branches:
      - master
      - 'release/**'
      - 'feature/**'

jobs:
  API-Test-and-Code-Quality-Gate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Maven 3.9.1
      uses: s4u/setup-maven-action@v1.10.0
      with:
        java-version: 17
        maven-version: 3.9.1
        
    - name: Test API
      run: mvn clean verify -Pdev

    - name: Archive api test execution results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: api-test-report
        path: target/TestExecutionReport.html

    - name: Check code quality
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=task-vault -Dsonar.organization=nishadchayanakhawa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true  
  
  UI-Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Maven 3.9.1
      uses: s4u/setup-maven-action@v1.10.0
      with:
        java-version: 17
        maven-version: 3.9.1
        
    - name: Test UI
      run: mvn clean verify -Pqa

    - name: Archive ui test execution results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ui-test-report.html
        path: target/TestExecutionReport.html
